//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.225.
// 
#pragma warning disable 1591

namespace ClientWSLogin.deetc.sd {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSLoginSoap", Namespace="http://deetc.isel.ipl.pt/SD/")]
    public partial class WSLogin : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private SoapHdLogin soapHdLoginValueField;
        
        private SoapHdMoreInfo soapHdMoreInfoValueField;
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private OtherHeader otherHeaderValueField;
        
        private System.Threading.SendOrPostCallback OtherMethOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSLogin() {
            this.Url = global::ClientWSLogin.Properties.Settings.Default.ClientWSLogin_deetc_sd_WSLogin;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public SoapHdLogin SoapHdLoginValue {
            get {
                return this.soapHdLoginValueField;
            }
            set {
                this.soapHdLoginValueField = value;
            }
        }
        
        public SoapHdMoreInfo SoapHdMoreInfoValue {
            get {
                return this.soapHdMoreInfoValueField;
            }
            set {
                this.soapHdMoreInfoValueField = value;
            }
        }
        
        public OtherHeader OtherHeaderValue {
            get {
                return this.otherHeaderValueField;
            }
            set {
                this.otherHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event OtherMethCompletedEventHandler OtherMethCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SoapHdLoginValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("SoapHdMoreInfoValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://deetc.isel.ipl.pt/SD/Login", RequestNamespace="http://deetc.isel.ipl.pt/SD/", ResponseNamespace="http://deetc.isel.ipl.pt/SD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Login(string msg) {
            object[] results = this.Invoke("Login", new object[] {
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string msg) {
            this.LoginAsync(msg, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string msg, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        msg}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("OtherHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://deetc.isel.ipl.pt/SD/OtherMeth", RequestNamespace="http://deetc.isel.ipl.pt/SD/", ResponseNamespace="http://deetc.isel.ipl.pt/SD/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OtherMeth() {
            object[] results = this.Invoke("OtherMeth", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OtherMethAsync() {
            this.OtherMethAsync(null);
        }
        
        /// <remarks/>
        public void OtherMethAsync(object userState) {
            if ((this.OtherMethOperationCompleted == null)) {
                this.OtherMethOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOtherMethOperationCompleted);
            }
            this.InvokeAsync("OtherMeth", new object[0], this.OtherMethOperationCompleted, userState);
        }
        
        private void OnOtherMethOperationCompleted(object arg) {
            if ((this.OtherMethCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OtherMethCompleted(this, new OtherMethCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://deetc.isel.ipl.pt/SD/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://deetc.isel.ipl.pt/SD/", IsNullable=false)]
    public partial class SoapHdLogin : System.Web.Services.Protocols.SoapHeader {
        
        private string userNameField;
        
        private string tokenKeyField;
        
        private TimeStamp tsField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string TokenKey {
            get {
                return this.tokenKeyField;
            }
            set {
                this.tokenKeyField = value;
            }
        }
        
        /// <remarks/>
        public TimeStamp ts {
            get {
                return this.tsField;
            }
            set {
                this.tsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://deetc.isel.ipl.pt/SD/")]
    public partial class TimeStamp {
        
        private System.DateTime dtInField;
        
        private System.DateTime dtOutField;
        
        /// <remarks/>
        public System.DateTime dtIn {
            get {
                return this.dtInField;
            }
            set {
                this.dtInField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime dtOut {
            get {
                return this.dtOutField;
            }
            set {
                this.dtOutField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://deetc.isel.ipl.pt/SD/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://deetc.isel.ipl.pt/SD/", IsNullable=false)]
    public partial class SoapHdMoreInfo : System.Web.Services.Protocols.SoapHeader {
        
        private string infoField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://deetc.isel.ipl.pt/SD/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://deetc.isel.ipl.pt/SD/", IsNullable=false)]
    public partial class OtherHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string[] tabstrField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string[] tabstr {
            get {
                return this.tabstrField;
            }
            set {
                this.tabstrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void OtherMethCompletedEventHandler(object sender, OtherMethCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OtherMethCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OtherMethCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591