//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFclient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pessoa", Namespace="http://schemas.datacontract.org/2004/07/Contratos")]
    [System.SerializableAttribute()]
    public partial class Pessoa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServiceOla")]
    public interface IServiceOla {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOla/olaSimples", ReplyAction="http://tempuri.org/IServiceOla/olaSimplesResponse")]
        string olaSimples(string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOla/olaPessoa", ReplyAction="http://tempuri.org/IServiceOla/olaPessoaResponse")]
        string olaPessoa(WCFclient.ServiceReference1.Pessoa pes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOla/getPessoa", ReplyAction="http://tempuri.org/IServiceOla/getPessoaResponse")]
        WCFclient.ServiceReference1.Pessoa getPessoa(string firstName, string lastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOla/changeState", ReplyAction="http://tempuri.org/IServiceOla/changeStateResponse")]
        void changeState(int val);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOla/getState", ReplyAction="http://tempuri.org/IServiceOla/getStateResponse")]
        int getState();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOla/teste", ReplyAction="http://tempuri.org/IServiceOla/testeResponse")]
        string[] teste(string[] str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOla/getDataMTOM", ReplyAction="http://tempuri.org/IServiceOla/getDataMTOMResponse")]
        byte[] getDataMTOM(byte[] arg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOla/division", ReplyAction="http://tempuri.org/IServiceOla/divisionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.DivideByZeroException), Action="http://tempuri.org/IServiceOla/divisionDivideByZeroExceptionFault", Name="DivideByZeroException", Namespace="http://schemas.datacontract.org/2004/07/System")]
        int division(int a, int b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOlaChannel : WCFclient.ServiceReference1.IServiceOla, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOlaClient : System.ServiceModel.ClientBase<WCFclient.ServiceReference1.IServiceOla>, WCFclient.ServiceReference1.IServiceOla {
        
        public ServiceOlaClient() {
        }
        
        public ServiceOlaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOlaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOlaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOlaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string olaSimples(string nome) {
            return base.Channel.olaSimples(nome);
        }
        
        public string olaPessoa(WCFclient.ServiceReference1.Pessoa pes) {
            return base.Channel.olaPessoa(pes);
        }
        
        public WCFclient.ServiceReference1.Pessoa getPessoa(string firstName, string lastName) {
            return base.Channel.getPessoa(firstName, lastName);
        }
        
        public void changeState(int val) {
            base.Channel.changeState(val);
        }
        
        public int getState() {
            return base.Channel.getState();
        }
        
        public string[] teste(string[] str) {
            return base.Channel.teste(str);
        }
        
        public byte[] getDataMTOM(byte[] arg) {
            return base.Channel.getDataMTOM(arg);
        }
        
        public int division(int a, int b) {
            return base.Channel.division(a, b);
        }
    }
}
