//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.225.
// 
#pragma warning disable 1591

namespace ClienteBookService.SD {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BookServiceSoap", Namespace="http://DEETC.SES.SD")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class BookService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private UmSoapHeader umSoapHeaderValueField;
        
        private System.Threading.SendOrPostCallback getISBNOperationCompleted;
        
        private System.Threading.SendOrPostCallback getBookPriceOperationCompleted;
        
        private System.Threading.SendOrPostCallback submitPOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback getbookOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BookService() {
            this.Url = global::ClienteBookService.Properties.Settings.Default.ClienteBookService_SD_BookService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public UmSoapHeader UmSoapHeaderValue {
            get {
                return this.umSoapHeaderValueField;
            }
            set {
                this.umSoapHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getISBNCompletedEventHandler getISBNCompleted;
        
        /// <remarks/>
        public event getBookPriceCompletedEventHandler getBookPriceCompleted;
        
        /// <remarks/>
        public event submitPOrderCompletedEventHandler submitPOrderCompleted;
        
        /// <remarks/>
        public event getbookCompletedEventHandler getbookCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UmSoapHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://DEETC.SES.SD/getISBN", RequestNamespace="http://DEETC.SES.SD", ResponseNamespace="http://DEETC.SES.SD", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getISBN(string title) {
            object[] results = this.Invoke("getISBN", new object[] {
                        title});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getISBNAsync(string title) {
            this.getISBNAsync(title, null);
        }
        
        /// <remarks/>
        public void getISBNAsync(string title, object userState) {
            if ((this.getISBNOperationCompleted == null)) {
                this.getISBNOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetISBNOperationCompleted);
            }
            this.InvokeAsync("getISBN", new object[] {
                        title}, this.getISBNOperationCompleted, userState);
        }
        
        private void OngetISBNOperationCompleted(object arg) {
            if ((this.getISBNCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getISBNCompleted(this, new getISBNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://DEETC.SES.SD/getBookPrice", RequestNamespace="http://DEETC.SES.SD", ResponseNamespace="http://DEETC.SES.SD", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public float getBookPrice(string isbn) {
            object[] results = this.Invoke("getBookPrice", new object[] {
                        isbn});
            return ((float)(results[0]));
        }
        
        /// <remarks/>
        public void getBookPriceAsync(string isbn) {
            this.getBookPriceAsync(isbn, null);
        }
        
        /// <remarks/>
        public void getBookPriceAsync(string isbn, object userState) {
            if ((this.getBookPriceOperationCompleted == null)) {
                this.getBookPriceOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBookPriceOperationCompleted);
            }
            this.InvokeAsync("getBookPrice", new object[] {
                        isbn}, this.getBookPriceOperationCompleted, userState);
        }
        
        private void OngetBookPriceOperationCompleted(object arg) {
            if ((this.getBookPriceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBookPriceCompleted(this, new getBookPriceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://DEETC.SES.SD/submitPOrder", RequestNamespace="http://DEETC.SES.SD", ResponseNamespace="http://DEETC.SES.SD", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string submitPOrder(PurchaseOrder po) {
            object[] results = this.Invoke("submitPOrder", new object[] {
                        po});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void submitPOrderAsync(PurchaseOrder po) {
            this.submitPOrderAsync(po, null);
        }
        
        /// <remarks/>
        public void submitPOrderAsync(PurchaseOrder po, object userState) {
            if ((this.submitPOrderOperationCompleted == null)) {
                this.submitPOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsubmitPOrderOperationCompleted);
            }
            this.InvokeAsync("submitPOrder", new object[] {
                        po}, this.submitPOrderOperationCompleted, userState);
        }
        
        private void OnsubmitPOrderOperationCompleted(object arg) {
            if ((this.submitPOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.submitPOrderCompleted(this, new submitPOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://DEETC.SES.SD/getbook", RequestNamespace="http://DEETC.SES.SD", ResponseNamespace="http://DEETC.SES.SD", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Book[] getbook(string isbn, int qty) {
            object[] results = this.Invoke("getbook", new object[] {
                        isbn,
                        qty});
            return ((Book[])(results[0]));
        }
        
        /// <remarks/>
        public void getbookAsync(string isbn, int qty) {
            this.getbookAsync(isbn, qty, null);
        }
        
        /// <remarks/>
        public void getbookAsync(string isbn, int qty, object userState) {
            if ((this.getbookOperationCompleted == null)) {
                this.getbookOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetbookOperationCompleted);
            }
            this.InvokeAsync("getbook", new object[] {
                        isbn,
                        qty}, this.getbookOperationCompleted, userState);
        }
        
        private void OngetbookOperationCompleted(object arg) {
            if ((this.getbookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getbookCompleted(this, new getbookCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://DEETC.SES.SD")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://DEETC.SES.SD", IsNullable=false)]
    public partial class UmSoapHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string anythingField;
        
        private int[] inteirosField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string anything {
            get {
                return this.anythingField;
            }
            set {
                this.anythingField = value;
            }
        }
        
        /// <remarks/>
        public int[] inteiros {
            get {
                return this.inteirosField;
            }
            set {
                this.inteirosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://DEETC.SES.SD")]
    public partial class Book {
        
        private string isbnField;
        
        private string titleField;
        
        private int quantityField;
        
        private float priceField;
        
        /// <remarks/>
        public string isbn {
            get {
                return this.isbnField;
            }
            set {
                this.isbnField = value;
            }
        }
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public int quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public float price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://DEETC.SES.SD")]
    public partial class PTAddress {
        
        private string nomeField;
        
        private string ruaField;
        
        private int[] numeroField;
        
        private string cidadeField;
        
        private string codigopostalField;
        
        /// <remarks/>
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string rua {
            get {
                return this.ruaField;
            }
            set {
                this.ruaField = value;
            }
        }
        
        /// <remarks/>
        public int[] numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public string cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
            }
        }
        
        /// <remarks/>
        public string codigopostal {
            get {
                return this.codigopostalField;
            }
            set {
                this.codigopostalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://DEETC.SES.SD")]
    public partial class PurchaseOrder {
        
        private string accountNameField;
        
        private int accountNumberField;
        
        private PTAddress paddressField;
        
        private Book itemBookField;
        
        private object[] tField;
        
        /// <remarks/>
        public string accountName {
            get {
                return this.accountNameField;
            }
            set {
                this.accountNameField = value;
            }
        }
        
        /// <remarks/>
        public int accountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        public PTAddress paddress {
            get {
                return this.paddressField;
            }
            set {
                this.paddressField = value;
            }
        }
        
        /// <remarks/>
        public Book itemBook {
            get {
                return this.itemBookField;
            }
            set {
                this.itemBookField = value;
            }
        }
        
        /// <remarks/>
        public object[] t {
            get {
                return this.tField;
            }
            set {
                this.tField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getISBNCompletedEventHandler(object sender, getISBNCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getISBNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getISBNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getBookPriceCompletedEventHandler(object sender, getBookPriceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBookPriceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBookPriceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public float Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((float)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void submitPOrderCompletedEventHandler(object sender, submitPOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class submitPOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal submitPOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getbookCompletedEventHandler(object sender, getbookCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getbookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getbookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Book[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Book[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591